### ISSUE TITLE
Coinhive being discontinued

### ISSUE THREAD

**Issue by ryanwryan** [sau412/coinhive_pool#2]
I read today that coinhive was being discontinued. This is right after I went to sign up with them to try out your software.

Is there any alternative?

https://coinhive.com/blog/en/discontinuation-of-coinhive

**Comment by sau412** [comment]
Yes, some time ago I implemented two another miners, JSEcoin and coinimp.

Coinhive miner will be hidden from site when I reach minimum withdraw amount, 0.02 XMR (currently 0.01945 XMR)
